name = "Affix"
badges = ["github-actions/linux.yaml", "github-actions/windows.yaml", "github-actions/osx.yaml", "github-actions/freebsd.yaml", "metacpan"]
module_maker = "ModuleBuildTiny"
authority = "cpan:SANKO"
static_install = "auto"
license = "artistic_2"
requires_external_bin=["$^X') if 0;\nuse lib '.';use builder::Affix; builder::Affix::Build_PL();\nexit;('1"]
markdown_maker = "Pod::Markdown::Github"
readme_from = 'lib/Affix.pod'
abstract_from = 'lib/Affix.pod'
authors_from = 'lib/Affix.pod'

[release]
hooks=[
    'tidyall -a'
]

[no_index]
directory=[
    "t",
    "xt",
    "inc",
    "share",
    "eg",
    "examples",
    "author",
    "builder",
    "dyncall"
]

[Metadata]
X_No_Archive = 'Yes'
