[package]
name = "affix_rust"
version = "0.1.0"
edition = "2021"
authors = ["Sanko Robinson"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
crate-type = ["dylib"]
#crate-type = ["cdylib"]
