name: Caching with perlbrew

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  install_perl:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
        perl:
          - 5.36.0
          #- 5.34.1
          #- 5.32.1
          #- 5.30.3
          #- 5.28.3
          #- 5.26.3
        flags:
          - --64int
          - --thread
          - --ld
          - --multi
          - ""
    name: "${{ matrix.os }}-${{ matrix.perl }}${{ matrix.flags }}"
    steps:
      - uses: actions/checkout@v3

      - name: Cache perl
        uses: actions/cache@v3
        id: cache-perl
        with:
          path: ~/perl5/perlbrew/
          key: ${{ matrix.os }}-perl-v${{ matrix.perl }}${{ matrix.flags }}

      - name: Cache dev environment on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/cache@v3
        id: cache-dev-env
        with:
          path: ~/dev-env
          key: ${{ matrix.os }}-dev

      - name: Install dev environment on Windows
        if: ${{ steps.cache-dev-env.outputs.cache-hit != 'true' && matrix.os == 'windows-latest' }}
        shell: cmd
        run: >
          cpanm -n -v Perl::Dist::Strawberry

      - name: "Set up perl ${{ matrix.perl }} with perlbrew"
        if: ${{ steps.cache-perl.outputs.cache-hit != 'true' && matrix.os != 'windows-latest' }}
        shell: bash
        run: >
             \curl -L https://install.perlbrew.pl | bash

             source ~/perl5/perlbrew/etc/bashrc

             perlbrew available

             perlbrew install-cpanm

             perlbrew install --switch --verbose perl-${{ matrix.perl }} --as cache-${{ matrix.os }}${{ matrix.perl }}${{ matrix.flags }} -j 12 --notest --noman ${{ matrix.flags }}

             perlbrew clean

      - name: "Set up perl ${{ matrix.perl }} with perlbrew"
        if: ${{ steps.cache-perl.outputs.cache-hit != 'true' && matrix.os == 'windows-latest' }}
        shell: cmd
        run: >
          C:\STRAWB~1\perl\site\bin\perldist_strawberry.bat -wixbin_dir="C:\Program Files (x86)\WiX Toolset v3.11\bin" -image_dir="%HOME%\perl5" -job "<dist_sharedir>/64bit-${{matrix.perl}}.1.pp" -notest_modules -notest_core -restorepoints

      - name: "Testing on chached perl ${{ matrix.os }}-${{ matrix.perl }}(${{ matrix.flags }})"
        shell: bash
        run: |
             source ~/perl5/perlbrew/etc/bashrc

             perl -v

             cpanm -nq --installdeps --with-develop --with-recommends .

             cpanm -v .
      - name: "perl -V"
        shell: bash
        run: |
             source ~/perl5/perlbrew/etc/bashrc

             perl -V