name: MacOS

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
    schedule:
        - cron: '42 5 * * 0'

jobs:
  install_perl:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        exclude:
          - os: macos-latest
            flags: -Dusequadmath
          - os: macos-latest
            flags: --thread
        os:
          - macos-latest
        perl:
          - 5.38.0
        flags:
          - --64int
          - --thread
          - --ld
          - --multi
          - -Dusequadmath
          - ""
    name: "${{ matrix.os }}-${{ matrix.perl }}${{ matrix.flags }}"
    steps:
      - uses: actions/checkout@v3

      - name: Cache perl
        uses: actions/cache@v3
        id: cache-perl
        with:
          path: ~/perl5/perlbrew/
          key: ${{ matrix.os }}-perl-v${{ matrix.perl }}${{ matrix.flags }}

      - name: "Build perl ${{ matrix.perl }} with perlbrew"
        if: ${{ steps.cache-perl.outputs.cache-hit != 'true' }}
        shell: bash
        run: >
             \curl -L https://install.perlbrew.pl | bash

             source ~/perl5/perlbrew/etc/bashrc

             perlbrew available

             perlbrew install-cpanm

             perlbrew install --switch --verbose --as cache-${{ matrix.os }}${{ matrix.perl }}${{ matrix.flags }} -j 12 --notest --noman ${{ matrix.flags }} perl-${{ matrix.perl }}

      - name: "Install deps"
        shell: bash
        run: |
             source ~/perl5/perlbrew/etc/bashrc

             perlbrew list

             perlbrew switch cache-${{ matrix.os }}${{ matrix.perl }}${{ matrix.flags }}

             perl -V

             cpanm --installdeps --notest .

      - name: "Testing on chached perl ${{ matrix.os }}-${{ matrix.perl }}(${{ matrix.flags }})"
        shell: bash
        run: |
             source ~/perl5/perlbrew/etc/bashrc

             perlbrew list

             perlbrew switch cache-${{ matrix.os }}${{ matrix.perl }}${{ matrix.flags }}

             perl -V

             cpanm --test-only -v .
